baseURL: "https://aminrb.me/"
languageCode: "en-us"
title: "Amin Rashidbeigi"
theme: "PaperMod"
enableRobotsTXT: true

permalinks:
  posts: /:slug/

params:
  description: "Amin Rashidbeigi's personal website"
  author: Amin Rashidbeigi
  comments: false
  ShowToc: true
  defaultTheme: auto
  ShowShareButtons: false
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  images: ["papermod-cover.png"]
  cover:
    linkFullImages: true

  profileMode:
    enabled: false
    title: A software engineer!
    imageUrl: "avatar.png"
    imageTitle: my image
    imageWidth: 120
    imageHeight: 120
    buttons:
      - name: Posts
        url: posts
      - name: CSV
        url: amin-rashidbeigi-cv-feb2023.pdf
  homeInfoParams:
    Title: "Hi there! ๐"
    Content: >
      Iโm Amin, a software engineer navigating the joys and challenges of tech life. On this site, I share my thoughts on software engineering, team leadership, and everything in between.


      Curious to know more about me? Head over to my [about page](/about/).


      If youโre a Persian reader, you can follow my [Telegram channel](https://t.me/aminrbg) for updates on new posts.


      And hey, Iโd love to hear from you! Feel free to connect with me on [Twitter](https://twitter.com/AminRashidbeigi) or [LinkedIn](https://www.linkedin.com/in/amin-rashidbeigi)โwhether you have questions, ideas to share, or just want to say hi :)
  socialIcons:
    - name: x
      url: "https://x.com/AminRashidbeigi"
    - name: linkedin
      url: "https://www.linkedin.com/in/amin-rashidbeigi"
    - name: github
      url: "https://github.com/aminrashidbeigi"
    # - name: medium
    # url: "https://medium.com/@amin.rashidbeigi"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/5714900/amin-rashidbeigi"
    - name: goodreads
      url: "https://www.goodreads.com/user/show/47262588-amin-rashidbeigi"
    - name: telegram
      url: "https://t.me/aminrbg"
    # - name: cv
    #   url: "https://aminrb.me/amin-rashidbeigi-cv-feb2023.pdf"
  assets:
    disableHLJS: true

markup:
  highlight:
    # anchorLineNos: false
    # codeFences: true
    # guessSyntax: true
    # hl_Lines: ""
    # hl_inline: false
    # lineAnchors: ""
    # lineNoStart: 1
    # lineNos: false
    # lineNumbersInTable: true
    noClasses: false
    # noHl: false
    # style: monokai
    # tabWidth: 4
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 1
    # - identifier: about
    #   name: About
    #   url: /about/
    #   weight: 2
    # - identifier: subscribe
    #   name: Subscribe
    #   url: https://aminrbme.beehiiv.com/subscribe/
    #   weight: 2
    - identifier: X
      name: X
      url: https://x.com/AminRashidbeigi
      weight: 2
    - identifier: side-projects
      name: Side Projects
      url: /side-projects/
      weight: 3

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
  fa:
    languageName: "ูุงุฑุณ"
    languagedirection: rtl
    weight: 2
    title: ุงูู ุฑุดุฏุจฺฏ
    params:
      author: ุงูู ุฑุดุฏุจฺฏ
      description: "ุตูุญูู ุดุฎุต ุงูู ุฑุดุฏุจฺฏ"
      profileMode:
        enabled: false
        title: ฺฉ ูููุฏุณ ูุฑูโุงูุฒุงุฑ!
        imageUrl: "avatar.png"
        imageTitle: my image
        imageWidth: 120
        imageHeight: 120
        buttons:
          - name: ููุดุชูโูุง
            url: posts
          - name: ุฑุฒููู
            url: amin-rashidbeigi-cv-feb2023.pdf
      homeInfoParams:
        Title: ุณูุงู! ๐
        Content: >
          ูู ุงูู ูุณุชูุ ูููุฏุณ ูุฑูโุงูุฒุงุฑู ู ุจู ูุดุงูุฏูุ ุชุญูู ู ุญู ูุดฺฉูุงุช ูุฑูโุงูุฒุงุฑ ู ุงุฑุชุจุงุทุงุช ุงูุณุงู ุญูู ูุณุฆูู ุนูุงููโููุฏู! ุงฺฏุฑ ฺฉูุฌฺฉุงู ฺฉู ุจุดุชุฑ ุฏุฑุจุงุฑูู ูู ุจุฏูู ุจู ุตูุญูู [ุฏุฑุจุงุฑูโู ูู](about/) ุณุฑ ุจุฒู.


          ูู ุฏุฑ ุญุงู ุญุงุถุฑ ุจู ุตูุฑุช ูุฑุชุจโุชุฑ ุชู  [ฺฉุงูุงู ุชูฺฏุฑุงูู](https://t.me/aminrbg) ูโููุณู ู ุงฺฏุฑ ุจู ููุถูุนุงุช ุงุดุงุฑูโุดุฏู ุนูุงููโููุฏ ุญุชูุงู ู ุณุฑ ุจูุด ุจุฒู.


          ุงฺฏุฑ ูู ูโุฎูุง ุฏุฑ ููุฑุฏ ููุถูุน ฺฏูพ ุจุฒููุ ุงุฏูโุง ุฑู ุจุงูุงู ุจู ุงุดุชุฑุงฺฉ ุจุฐุงุฑ ุง ุตุฑูุงู ุจุง ูู ุจุดุชุฑ ุขุดูุง ุดูุ [ุงูุฌุง](ways-i-can-help/) ููฺฉ ุชููู ู ุฒูุงูโูุง ุฎุงูู ุฑู ูพุฏุง ูโฺฉู ู ูโุชููู ุจุง ูู ฺฏูุชโูโฺฏู ฺฉููุ ุง ุงู ฺฉู ุจูู ุงูู ุจุฒู.
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - identifier: posts
          name: ููุดุชูโูุง
          url: /posts/
          weight: 1
        - identifier: about
          name: ุฏุฑุจุงุฑูู ูู
          url: /about/
          weight: 2
        # - identifier: ways-i-help
        #   name: ุฎุฏูุงุช
        #   url: /ways-i-help/
        #   weight: 3
        # - identifier: side-projects
        #   name: ูพุฑูฺูโูุง
        #   url: /side-projects/
        #   weight: 3
        - identifier: telegram
          name: ฺฉุงูุงู ุชูฺฏุฑุงู
          url: https://t.me/aminrbg
          weight: 3
