baseURL: "https://aminrashidbeigi.github.io/"
languageCode: "en-us"
title: "Amin Rashidbeigi"
theme: "PaperMod"

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
    author: Theme PaperMod

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    # comments: false
    images: ["papermod-cover.png"]
    cover:
        linkFullImages: true

    profileMode:
        enabled: true
        title: A software engineer!
        imageUrl: "avatar.png"
        imageTitle: my image
        imageWidth: 120
        imageHeight: 120
        buttons:
            - name: Blog
              url: posts
            - name: CSV
              url: amin-rashidbeigi-cv-feb2023.pdf
    homeInfoParams:
        Title: "PaperMod"
        Content: >
            Welcome to demo of hugo's theme PaperMod.
            - **PaperMod** is a simple but fast and responsive theme with useful feature-set that enhances UX.
            - Do give a ğŸŒŸ on Github !
            - PaperMod is based on theme [Paper](https://github.com/nanxiaobei/hugo-paper).
    socialIcons:
        - name: github
          url: "https://github.com/aminrashidbeigi"
        - name: medium
          url: "https://medium.com/@amin.rashidbeigi"
        - name: linkedin
          url: "https://www.linkedin.com/in/amin-rashidbeigi"
        - name: twitter
          url: "https://twitter.com/AminRashidbeigi"
        - name: stackoverflow
          url: "https://stackoverflow.com/users/5714900/amin-rashidbeigi"
        - name: goodreads
          url: "https://www.goodreads.com/user/show/47262588-amin-rashidbeigi"


languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
    fa:
        languageName: "ÙØ§Ø±Ø³ÛŒ"
        languagedirection: rtl
        weight: 2
        title: Ø§Ù…ÛŒÙ† Ø±Ø´ÛŒØ¯Ø¨ÛŒÚ¯ÛŒ
        profileMode:
            enabled: true
            title: ÛŒÚ© Ù…Ù‡Ù†Ø¯Ø³ Ù†Ø±Ù…â€ŒØ§ÙØ²Ø§Ø±!
            imageUrl: "avatar.png"
            imageTitle: my image
            imageWidth: 120
            imageHeight: 120
            buttons:
            - name: ÙˆØ¨Ù„Ø§Ú¯
              url: posts
            - name: Ø±Ø²ÙˆÙ…Ù‡
              url: amin-rashidbeigi-cv-feb2023.pdf
        homeInfoParams:
            Title: "Ø³Ù„Ø§Ù… Ø®ÙˆØ´ Ø¢ÙˆÙ…Ø¯ÛŒØ¯ \U0001F44B"
            Content: Ø¨Ù‡ ÙˆØ¨Ø³Ø§ÛŒØª Ù…Ù† Ø®ÙˆØ´ Ø¢Ù…Ø¯ÛŒØ¯
        taxonomies:
          category: FAcategories
          tag: FAtags
          series: FAseries